### ISSUE TITLE
Filter List on Map Extents

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-latest-earthquakes#131]
When the restrictListToMap setting is enabled

**Comment by emartinez-usgs** [comment]
- Do not require leaflet. Use `/* global L */` instead.
- Since `L.LatLngBounds.contains` does not deal with the dateline/wrapping issue, it is cleaner to not use Leaflet classes here.
- Do not use `this`, prefer to use `_this`.

- In Catalog, listen for `change:restrictListToMap`.
  - When this occurs, start/stop listening for `change:mapposition`.
  - When change:mapposition handler executes, it should re-filter all data.
  - When `load` completes, it should check if `restrictListToMap` is true and if so, filter data before reset.
  - Map should not render `onMoveEnd` since this might cause a double render. Instead, render on catalog reset and `change:mapposition` events.
    - When change:mapposition occurs, check the previous map center (must hold reference to this internally). If center has changed significantly (> 90 deg lng ???) *and* `restrictListToMap` is false, then call render.
    - In render method, save reference to center position to render around (for above check).

There may be additional work to prevent multi-renders while ensuring rendering occurs as needed.

**Comment by emartinez-usgs** [comment]
- Update bounds check as discussed. Normalize point to bounds rather than vice-versa.
- Double-render occurs when enabling filter option.
- Triple render occurs when changing feed with filter option enabled.
- This is likely from using the _filteredCollection. Instead, consider modifying the GenericCollectionView to use a new `getDataToRender` method which, by default, returns the collection data array. Your sub-class could return the filtered array instead. This removes the double-bindings and supports filtering.

**Comment by emartinez-usgs** [comment]
Use local `latitude` variable in `boundsContain` when checking initial latitude filter (instead of `latlng[0]`).

Simplify normalization logic...
- No need for outer if-statement
- Simplify while-statements like so `while (longitude < minLongitude) { longitude += 360; }` and `while (longitude > maxLongitude) { longitude -= 360; }`
- Finally, simply `return (longitude >= minLongitude && longitude <= maxLongitude);`

Change moveend bindings on the map to use a private method that calls a public method in order to support runtime binding resolution and extension.

Remove `console.log` statements.

Use `Array.filter` as an optimization to the current filter loop.
Probably check `if (!_bounds || _this.boundsEmpty(_bounds)) { ... `
