### ISSUE TITLE
Application skeleton

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-latest-earthquakes#67]
Sets up application model, containers for various views.

**Comment by hasimpson-usgs** [comment]
When viewModes help property is true, application should show help view in a modal dialog.  When help view modal dialog is closed, application should set viewModes help property to false.   Be certain not to change other viewModes properties.  Use Util.extend, so that the model detects the update.

**Comment by emartinez-usgs** [comment]
Some comments based on changes made in #98:

core/Config
  Stores a set of collections which define the available options to dispay
  in the interface. Things like "basemaps", "overlays", etc... Makes no attempt
  to stay in sync with current state of model (in fact, has no reference to
  the model at all). Exposes convenience methods:

  + getCollection(String name) :: Collection
  + getObject(Collection collection, String id) :: Object

  + getBaseMap(String id) :: Object
  + getOverlay(String id) :: Object
  ... etc ...


core/UrlManager
  Receives a model and a config. The model provides information about the
  current application state (i.e. which options are selected) while the config
  provides lookup tables (Collections) useful in order to map IDs to Objects and
  vice-versa.

  Binds to model change events, and when such changes occur, maps the model
  state into a url configuration string and updates the url on the window

  Binds to hashChange events and when such changes occur, parses
  the current url state into an object and sets the model properties to match.


latesteqs/LatestEarthquakes
  Scaffolds framework and creates subviews/utilities.

  Binds to model change:viewModes and manages application view mode state
  accordingly.
