### ISSUE TITLE
map/EarthquakeLayer

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-latest-earthquakes#68]
map/EarthquakeLayer

Try implementing as a leaflet geojson layer, see if performant enough.
Use existing styles for colors/sizes.

Add example page.
Add test.

**Comment by emartinez-usgs** [comment]
- Internally the layer only uses a collection. Should default to that and change reference to `_this.collection` and configuration property to `collection` to be more generic and less application-aware.

- Setting `earthquake-marker` class multiple places.
- Maybe be more aggressive about de-selecting items with a `querySelectorAll`
- Do classes need to be re-computed each time `getMarker` is called or can this be done only when the marker is initially created?
- The `_this.onClick` that is bound as a DOM event handler should be a private `_onClick` method. It can potentially simply call `_this.onClick` if desired.
- Tests
- The `_this.destroy` does not have a parent method to compose itself with.
- Alphabetize methods
- Remove unused classe(s)

**Comment by emartinez-usgs** [comment]
- All event bindings by reference (instead of name) should be done to a private method delegating to the instance method for subclassability (eg. render).
- Yes, desktop-specific styles should be done with media queries.
- Missing use strict in test file.
  - More generally, is jshint set up correctly, I'm seeing many pull requests with linting errors.
- Missing var declaration in test file (view)
- Unused import "Collection" in test file.
- Add test to destroy method. I'm relatively convinced the mystery issue @jdbrown-USGS was experiencing was tied to the failed destroy with the old `_this.destroy = Util.compose(function, undefined);` definition
-  Would it make sense to move `getLatLng` method to a utility class? It doesn't relay on instance properties and it could be useful to the ListView when restricting list to map.
- Just FYI - You can use spy.calledWith to check all the arguments at once. Might be simpler in the future.
- Implement test for render method
