### ISSUE TITLE
Download View

### ISSUE THREAD

**Issue by hasimpson-usgs** [usgs/earthquake-latest-earthquakes#96]
Should use the current feed/search and offer links for all available formats.

**Comment by hasimpson-usgs** [comment]
Should look at the object referenced by the feed property on the given model.  Use the URL off that object, replacing geojson with the various formats to generate download urls. The formats should be configurable on the download view.  Each format will have title, description and ID.

**Comment by emartinez-usgs** [comment]
- Be careful about vertical spacing between sections in the source code. Two blank lines between each major section, one blank line between items within a section.
- Example should not need to use XHR or fetch any data, the model should simply have a `feed` property whose value is an object that looks like what one might see in `latesteqs/LatestEarthquakesConfig`
- Instead of directly calling render in the example, try just setting the feed property after creating the view.
- Change output format (CSS) to use a vertical header/subheader layout. This will work better on small screens and with longer description text.
- Declare all variables at the top of the nearest closure
- When conditionally building strings, should use the Array.push approach.
- Do not use `metadata`, instead use the `feed` property to determine the URL
- Can not assume the `.geojson` is the end of the string. For searches this will most likely not be the case.
- Any `initialize` tests should be added to the `constructor` describe block

**Comment by emartinez-usgs** [comment]
- Should check to ensure collection.metadata is set in `getDownloadLinks` rather than in `render`. It is more important for the former than the latter so long as `getDownloadLinks` always returns an array (even if it is potentially empty).
- Generated markup should be properly encoded, either manually or by using `encodeURI` (or similar method).

**Comment by emartinez-usgs** [comment]
View is rendering too often. Probably unbind from model change events since you're never using the model. Perhaps change the signature so the model _is_ the collection (which never triggers change events), then bind to the reset as necessary.
