### ISSUE TITLE
Legend Control

### ISSUE THREAD

**Issue by hasimpson-usgs** [usgs/earthquake-latest-earthquakes#97]
Create a legend control in map/LegendControl

**Comment by emartinez-usgs** [comment]
- Styles should be updated to look/feel more like other hazdev-leaflet controls.
- Leaflet constructors using lower-case method names should not also use `new` keyword. Using lower-case method names is preferred.
- Prefer using JS objects for LatLng etc... when applicable. `center: [lat, lng]` rather than `center: L.latLng(lat, lng)`
- Styles should try to use direct descendent selectors when possible. Potentially just use more OOCSS classes.
- Double-check indentation/whitespace in general.
- When defining Leaflet extensions (controls, layers, etc...) always attach the `new Constructor` instance to L.ClassName as well as expose `L.className` functional constructor. Additionally, per our implementation guidelines, module.exports should be set to the functional constructor so as to not use the `new` keyword.
- Do not `require('leaflet');` rather use global L.
